[[plugins]]

  package = "netlify-plugin-flutter"

   [plugins.inputs]
    channel = "stable"

[build]

command = "dart run build_runner build --delete-conflicting-outputs"

command = "flutter build web --release"
publish = "build/web"